
package br.com.fiap.ws.client.governo;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Invoice", targetNamespace = "http://br.com.fiap.government/", wsdlLocation = "http://fiap-29scj-government.herokuapp.com/Service/Invoice?wsdl")
public class Invoice_Service
    extends Service
{

    private final static URL INVOICE_WSDL_LOCATION;
    private final static WebServiceException INVOICE_EXCEPTION;
    private final static QName INVOICE_QNAME = new QName("http://br.com.fiap.government/", "Invoice");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://fiap-29scj-government.herokuapp.com/Service/Invoice?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        INVOICE_WSDL_LOCATION = url;
        INVOICE_EXCEPTION = e;
    }

    public Invoice_Service() {
        super(__getWsdlLocation(), INVOICE_QNAME);
    }

    public Invoice_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), INVOICE_QNAME, features);
    }

    public Invoice_Service(URL wsdlLocation) {
        super(wsdlLocation, INVOICE_QNAME);
    }

    public Invoice_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, INVOICE_QNAME, features);
    }

    public Invoice_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Invoice_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Invoice
     */
    @WebEndpoint(name = "InvoicePort")
    public Invoice getInvoicePort() {
        return super.getPort(new QName("http://br.com.fiap.government/", "InvoicePort"), Invoice.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Invoice
     */
    @WebEndpoint(name = "InvoicePort")
    public Invoice getInvoicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://br.com.fiap.government/", "InvoicePort"), Invoice.class, features);
    }

    private static URL __getWsdlLocation() {
        if (INVOICE_EXCEPTION!= null) {
            throw INVOICE_EXCEPTION;
        }
        return INVOICE_WSDL_LOCATION;
    }

}
