
package br.com.fiap.ws.client.governo;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Invoice", targetNamespace = "http://br.com.fiap.government/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Invoice {


    /**
     * 
     * @param password
     * @param parameters
     * @param username
     * @return
     *     returns br.com.fiap.ws.client.governo.ListResponse
     */
    @WebMethod(action = "urn:ListInvoice")
    @WebResult(name = "listResponse", targetNamespace = "http://br.com.fiap.government/", partName = "parameters")
    public ListResponse list(
        @WebParam(name = "list", targetNamespace = "http://br.com.fiap.government/", partName = "parameters")
        List parameters,
        @WebParam(name = "username", targetNamespace = "http://br.com.fiap.government/", header = true, partName = "username")
        String username,
        @WebParam(name = "password", targetNamespace = "http://br.com.fiap.government/", header = true, partName = "password")
        String password);

    /**
     * 
     * @param password
     * @param parameters
     * @param username
     * @return
     *     returns br.com.fiap.ws.client.governo.GenerateResponse
     * @throws Exception_Exception
     */
    @WebMethod(action = "urn:GenerateInvoice")
    @WebResult(name = "generateResponse", targetNamespace = "http://br.com.fiap.government/", partName = "parameters")
    public GenerateResponse generate(
        @WebParam(name = "generate", targetNamespace = "http://br.com.fiap.government/", partName = "parameters")
        Generate parameters,
        @WebParam(name = "username", targetNamespace = "http://br.com.fiap.government/", header = true, partName = "username")
        String username,
        @WebParam(name = "password", targetNamespace = "http://br.com.fiap.government/", header = true, partName = "password")
        String password)
        throws Exception_Exception
    ;

}
