
package br.com.fiap.ws.client.governo;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Taxes", targetNamespace = "http://br.com.fiap.government/", wsdlLocation = "http://fiap-29scj-government.herokuapp.com/Service/Taxes?wsdl")
public class Taxes_Service
    extends Service
{

    private final static URL TAXES_WSDL_LOCATION;
    private final static WebServiceException TAXES_EXCEPTION;
    private final static QName TAXES_QNAME = new QName("http://br.com.fiap.government/", "Taxes");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://fiap-29scj-government.herokuapp.com/Service/Taxes?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TAXES_WSDL_LOCATION = url;
        TAXES_EXCEPTION = e;
    }

    public Taxes_Service() {
        super(__getWsdlLocation(), TAXES_QNAME);
    }

    public Taxes_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), TAXES_QNAME, features);
    }

    public Taxes_Service(URL wsdlLocation) {
        super(wsdlLocation, TAXES_QNAME);
    }

    public Taxes_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TAXES_QNAME, features);
    }

    public Taxes_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Taxes_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Taxes
     */
    @WebEndpoint(name = "TaxesPort")
    public Taxes getTaxesPort() {
        return super.getPort(new QName("http://br.com.fiap.government/", "TaxesPort"), Taxes.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Taxes
     */
    @WebEndpoint(name = "TaxesPort")
    public Taxes getTaxesPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://br.com.fiap.government/", "TaxesPort"), Taxes.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TAXES_EXCEPTION!= null) {
            throw TAXES_EXCEPTION;
        }
        return TAXES_WSDL_LOCATION;
    }

}
